-- MySQL Script generated by MySQL Workbench
-- Sáb 20 Ago 2016 20:06:37 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym` DEFAULT CHARACTER SET utf8 ;
USE `gym` ;

-- -----------------------------------------------------
-- Table `gym`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;

--
-- Dumping data for table `usuario`
--

INSERT INTO `usuario` (`id`, `nome`, `email`, `senha`) VALUES
(1, 'marco', 'marco@gmail.com', '202cb962ac59075b964b07152d234b70');


-- -----------------------------------------------------
-- Table `gym`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`ficha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `dias_semana` VARCHAR(256) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ficha_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_ficha_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`exercicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `grupos_musculares` VARCHAR(256) NOT NULL,
  `ficha_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercicio_ficha1_idx` (`ficha_id` ASC),
  CONSTRAINT `fk_exercicio_ficha1`
    FOREIGN KEY (`ficha_id`)
    REFERENCES `gym`.`ficha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`serie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('peso', 'tempo') NOT NULL,
  `repeticoes` INT NULL,
  `peso` INT NULL,
  `tempo` INT NULL,
  `exercicio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serie_exercicio_idx` (`exercicio_id` ASC),
  CONSTRAINT `fk_serie_exercicio`
    FOREIGN KEY (`exercicio_id`)
    REFERENCES `gym`.`exercicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`treino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_treino_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_treino_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`exercicio_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`exercicio_treino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `grupos_musculares` VARCHAR(256) NOT NULL,
  `treino_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exercicio_treino_treino1_idx` (`treino_id` ASC),
  CONSTRAINT `fk_exercicio_treino_treino1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym`.`treino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`serie_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`serie_treino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('peso', 'tempo') NOT NULL,
  `repeticoes` INT NULL,
  `peso` INT NULL,
  `tempo` INT NULL,
  `exercicio_treino_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serie_treino_exercicio_treino1_idx` (`exercicio_treino_id` ASC),
  CONSTRAINT `fk_serie_treino_exercicio_treino1`
    FOREIGN KEY (`exercicio_treino_id`)
    REFERENCES `gym`.`exercicio_treino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
